services:
  app:
    build: .
    container_name: pki-2fa-app
    ports:
      - "8080:8080"
    volumes:
      - seed-data:/data
      - ./student_private.pem:/app/student_private.pem:ro
      - ./student_public.pem:/app/student_public.pem:ro
      - ./instructor_public.pem:/app/instructor_public.pem:ro
    restart: unless-stopped

volumes:
  seed-data: